package org.longxin.domains;

// Generated 2015-1-10 20:08:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Feature generated by hbm2java
 */
@Entity
@Table(name = "feature", catalog = "longxin")
public class Feature implements java.io.Serializable, Cloneable
{
	private static final long serialVersionUID = 5379079441355132505L;
	private Integer id;
	private Product product;
	private String featureName;
	private Set<Function> functions = new HashSet<Function>(0);

	public Feature()
	{
	}

	public Feature(Product product, String featureName)
	{
		this.product = product;
		this.featureName = featureName;
	}

	public Feature(Product product, String featureName, Set<Function> functions)
	{
		this.product = product;
		this.featureName = featureName;
		this.functions = functions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT", nullable = false)
	public Product getProduct()
	{
		return this.product;
	}

	public void setProduct(Product product)
	{
		this.product = product;
	}

	@Column(name = "FEATURE_NAME", nullable = false, length = 128)
	public String getFeatureName()
	{
		return this.featureName;
	}

	public void setFeatureName(String featureName)
	{
		this.featureName = featureName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "feature")
	public Set<Function> getFunctions()
	{
		return this.functions;
	}

	public void setFunctions(Set<Function> functions)
	{
		this.functions = functions;
	}
	
	public Object clone() throws CloneNotSupportedException 
	{
		//TODO
		Feature cloned = (Feature) super.clone();
		cloned.setId(null);
		
		throw new CloneNotSupportedException();
	}

}
