package org.longxin.domains;

// Generated 2015-1-10 20:08:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Function generated by hbm2java
 */
@Entity
@Table(name = "function", catalog = "longxin")
public class Function implements java.io.Serializable
{
	private static final long serialVersionUID = 4289436799324846577L;
	private Integer id;
	private Feature feature;
	private String functionName;

	public Function()
	{
	}

	public Function(Feature feature)
	{
		this.feature = feature;
	}

	public Function(Feature feature, String functionName)
	{
		this.feature = feature;
		this.functionName = functionName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FEATURE", nullable = false)
	public Feature getFeature()
	{
		return this.feature;
	}

	public void setFeature(Feature feature)
	{
		this.feature = feature;
	}

	@Column(name = "FUNCTION_NAME", length = 128)
	public String getFunctionName()
	{
		return this.functionName;
	}

	public void setFunctionName(String functionName)
	{
		this.functionName = functionName;
	}

}
