package org.longxin.domains;

// Generated 2015-1-17 22:30:04 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * L1ComponentParameter generated by hbm2java
 */
@Entity
@Table(name = "l1_component_parameter", catalog = "longxin")
public class L1ComponentParameter extends ComponentParameter implements java.io.Serializable, Cloneable
{
    /**
	 * 
	 */
    private static final long serialVersionUID = -8558339055272345772L;

    public String CATEGORY = "L1COMPONENTPARAMETER";

    private L1Component l1Component;

    public L1ComponentParameter()
    {
    }

    public L1ComponentParameter(
        L1Component l1Component,
        String parameterName,
        String parameterValue,
        String valueScope,
        String unitName,
        String options)
    {
        this.l1Component = l1Component;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "L1_COMPONENT")
    public L1Component getL1Component()
    {
        return this.l1Component;
    }

    public void setL1Component(L1Component l1Component)
    {
        this.l1Component = l1Component;
    }

    protected Object clone() throws CloneNotSupportedException
    {
        L1ComponentParameter l1ComponentParameter = (L1ComponentParameter) super.clone();
        l1ComponentParameter.setId(null);
        return l1ComponentParameter;
    }

    @Override
    @Transient
    public String getCategory()
    {
        return this.CATEGORY;
    }
}
