package org.longxin.domains;

// Generated 2015-1-17 22:30:04 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * L1ComponentParameter generated by hbm2java
 */
@Entity
@Table(name = "l1_component_parameter", catalog = "longxin")
public class L1ComponentParameter implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = -8558339055272345772L;
	private Integer id;
	private L1Component l1Component;
	private String parameterName;
	private String parameterValue;
	private String valueScope;
	private String unitName;
	private String options;

	public L1ComponentParameter()
	{
	}

	public L1ComponentParameter(String parameterName)
	{
		this.parameterName = parameterName;
	}

	public L1ComponentParameter(L1Component l1Component, String parameterName,
			String parameterValue, String valueScope, String unitName,
			String options)
	{
		this.l1Component = l1Component;
		this.parameterName = parameterName;
		this.parameterValue = parameterValue;
		this.valueScope = valueScope;
		this.unitName = unitName;
		this.options = options;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "L1_COMPONENT")
	public L1Component getL1Component()
	{
		return this.l1Component;
	}

	public void setL1Component(L1Component l1Component)
	{
		this.l1Component = l1Component;
	}

	@Column(name = "PARAMETER_NAME", nullable = false, length = 128)
	public String getParameterName()
	{
		return this.parameterName;
	}

	public void setParameterName(String parameterName)
	{
		this.parameterName = parameterName;
	}

	@Column(name = "PARAMETER_VALUE", length = 256)
	public String getParameterValue()
	{
		return this.parameterValue;
	}

	public void setParameterValue(String parameterValue)
	{
		this.parameterValue = parameterValue;
	}

	@Column(name = "VALUE_SCOPE", length = 128)
	public String getValueScope()
	{
		return this.valueScope;
	}

	public void setValueScope(String valueScope)
	{
		this.valueScope = valueScope;
	}

	@Column(name = "UNIT_NAME", length = 45)
	public String getUnitName()
	{
		return this.unitName;
	}

	public void setUnitName(String unitName)
	{
		this.unitName = unitName;
	}

	@Column(name = "OPTIONS", length = 512)
	public String getOptions()
	{
		return this.options;
	}

	public void setOptions(String options)
	{
		this.options = options;
	}

}
