package org.longxin.domains;

// Generated 2015-1-17 22:30:04 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * L3ComponentParameter generated by hbm2java
 */
@Entity
@Table(name = "l3_component_parameter", catalog = "longxin")
public class L3ComponentParameter extends ComponentParameter implements java.io.Serializable, Cloneable
{
    /**
	 * 
	 */
    private static final long serialVersionUID = 4944996945861236995L;

    public String CATEGORY = "L3COMPONENTPARAMETER";

    private L3Component l3Component;

    public L3ComponentParameter()
    {
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "L3_COMPONENT")
    public L3Component getL3Component()
    {
        return l3Component;
    }

    public void setL3Component(L3Component l3Component)
    {
        this.l3Component = l3Component;
    }

    protected Object clone() throws CloneNotSupportedException
    {
        L3ComponentParameter l3ComponentParameter = (L3ComponentParameter) super.clone();
        l3ComponentParameter.setId(null);
        return l3ComponentParameter;
    }

    @Override
    @Transient
    public String getCategory()
    {
        return this.CATEGORY;
    }
}
