package org.longxin.domains;

// Generated 2015-1-17 22:30:04 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * L3ComponentParameter generated by hbm2java
 */
@Entity
@Table(name = "l3_component_parameter", catalog = "longxin")
public class L3ComponentParameter implements java.io.Serializable, Cloneable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 4944996945861236995L;
	private Integer id;
	private L3Component l3Component;
	private String parameterName;
	private String parameterValue;
	private String unitName;
	private String options;
	private String minValue;
	private String maxValue;
	private Boolean isDraft;
    private String draftValue;

	public L3ComponentParameter()
	{
	}

	public L3ComponentParameter(L3Component l3Component, String parameterName,
			String parameterValue, String valueScope, String unitName,
			String options)
	{
		this.l3Component = l3Component;
		this.parameterName = parameterName;
		this.parameterValue = parameterValue;
		this.unitName = unitName;
		this.options = options;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "L3_COMPONENT")
	public L3Component getL3Component()
	{
		return this.l3Component;
	}

	public void setL3Component(L3Component l3Component)
	{
		this.l3Component = l3Component;
	}

	@Column(name = "PARAMETER_NAME", length = 45)
	public String getParameterName()
	{
		return this.parameterName;
	}

	public void setParameterName(String parameterName)
	{
		this.parameterName = parameterName;
	}

	@Column(name = "PARAMETER_VALUE", length = 128)
	public String getParameterValue()
	{
		return this.parameterValue;
	}

	public void setParameterValue(String parameterValue)
	{
		this.parameterValue = parameterValue;
	}

	@Column(name = "UNIT_NAME", length = 45)
	public String getUnitName()
	{
		return this.unitName;
	}

	public void setUnitName(String unitName)
	{
		this.unitName = unitName;
	}

	@Column(name = "OPTIONS", length = 512)
	public String getOptions()
	{
		return this.options;
	}

	public void setOptions(String options)
	{
		this.options = options;
	}
	@Column(name = "MIN_VALUE", length = 128)
	public String getMinValue()
	{
		return minValue;
	}

	public void setMinValue(String minValue)
	{
		this.minValue = minValue;
	}

	@Column(name = "MAX_VALUE", length = 128)
	public String getMaxValue()
	{
		return maxValue;
	}

	public void setMaxValue(String maxValue)
	{
		this.maxValue = maxValue;
	}
	
	@Column(name = "IS_DRAFT")
    public Boolean getIsDraft()
    {
        return isDraft;
    }

    public void setIsDraft(Boolean isDraft)
    {
        this.isDraft = isDraft;
    }

    @Column(name = "DRAFT_VALUE", length = 256)
    public String getDraftValue()
    {
        return draftValue;
    }

    public void setDraftValue(String draftValue)
    {
        this.draftValue = draftValue;
    }
	
	protected Object clone() throws CloneNotSupportedException{
		L3ComponentParameter l3ComponentParameter = (L3ComponentParameter)super.clone();
		l3ComponentParameter.setId(null);
		return l3ComponentParameter;
	}
}
