package org.longxin.domains;

// Generated 2015-1-17 19:49:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "module", catalog = "longxin")
public class Module implements java.io.Serializable
{

	private static final long serialVersionUID = 610942910382178152L;
	private Integer id;
	private Feature feature;
	private String moduleName;
	private Boolean template;

	public Module()
	{
	}

	public Module(Feature feature)
	{
		this.feature = feature;
	}

	public Module(Feature feature, String moduleName, Boolean template)
	{
		this.feature = feature;
		this.moduleName = moduleName;
		this.template = template;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FEATURE", nullable = false)
	public Feature getFeature()
	{
		return this.feature;
	}

	public void setFeature(Feature feature)
	{
		this.feature = feature;
	}

	@Column(name = "MODULE_NAME", length = 128)
	public String getModuleName()
	{
		return this.moduleName;
	}

	public void setModuleName(String moduleName)
	{
		this.moduleName = moduleName;
	}

	@Column(name = "TEMPLATE")
	public Boolean getTemplate()
	{
		return this.template;
	}

	public void setTemplate(Boolean template)
	{
		this.template = template;
	}

}
